#!/usr/bin/env python3
"""DORAKULA WAF Bypass Engine berbasis GenAI.

Uses AI (Ollama) to generate payload obfuscation variants, encoding chains,
and novel bypass techniques. Falls back to rule-based encoding if AI unavailable.
"""
import logging, base64, urllib.parse, json, random, string
from typing import Dict, List, Any

logger = logging.getLogger(__name__)


class WAFBypassAI:
    """AI-powered WAF bypass payload generator."""

    ENCODING_LAYERS = ["url", "double_url", "base64", "unicode", "hex", "html_entity"]

    def __init__(self, ai_router=None):
        self.ai_router = ai_router
        self._successful_payloads: List[str] = []

    def generate_obfuscation(self, payload: str, waf_type: str = "generic") -> Dict:
        """Generate obfuscated variants of a payload for WAF bypass."""
        variants = []
        # Rule-based encoding chains (always available)
        variants.append({"technique": "url_encode", "payload": urllib.parse.quote(payload)})
        variants.append({"technique": "double_url_encode", "payload": urllib.parse.quote(urllib.parse.quote(payload))})
        variants.append({"technique": "base64", "payload": base64.b64encode(payload.encode()).decode()})
        # Unicode escape
        unicode_payload = "".join(f"\\u{ord(c):04x}" for c in payload)
        variants.append({"technique": "unicode_escape", "payload": unicode_payload})
        # Hex escape
        hex_payload = "".join(f"\\x{ord(c):02x}" for c in payload)
        variants.append({"technique": "hex_escape", "payload": hex_payload})
        # HTML entity
        html_payload = "".join(f"&#{ord(c)};" for c in payload)
        variants.append({"technique": "html_entity", "payload": html_payload})
        # Chunking (split payload)
        if len(payload) > 10:
            mid = len(payload) // 2
            variants.append({"technique": "chunked", "payload": f"{payload[:mid]}/**/{payload[mid:]}", "note": "SQL comment chunking"})
        # HPP (HTTP Parameter Pollution)
        variants.append({"technique": "hpp", "payload": f"{payload}&id={payload}", "note": "HPP duplicate param"})
        # Case variation
        case_payload = "".join(c.upper() if random.random() > 0.5 else c.lower() for c in payload)
        variants.append({"technique": "case_variation", "payload": case_payload})

        # AI-generated bypass (if available)
        ai_suggestion = None
        if self.ai_router and self.ai_router.ollama_available:
            try:
                prompt = f"Generate 3 WAF bypass variants for this payload against {waf_type} WAF. Payload: {payload}. Reply with JSON array of strings only."
                result = self.ai_router.query(prompt, task="quick", max_tokens=150)
                if result and "{" not in result[:5]:
                    ai_suggestion = result[:500]
            except Exception as e:
                logger.warning("WAF bypass AI query failed: %s", e)

        return {
            "original": payload,
            "waf_type": waf_type,
            "variants": variants,
            "ai_suggestion": ai_suggestion,
            "total_variants": len(variants),
        }

    def fingerprint_waf(self, response_headers: dict, status_code: int, body: str) -> Dict:
        """Identify WAF type from response characteristics."""
        waf_signatures = {
            "cloudflare": ["cloudflare", "cf-ray", "__cf_bm"],
            "safeline": ["safeline", "chaitin"],
            "modsecurity": ["mod_security", "modsecurity", "nginx-mod-security"],
            "akamai": ["akamai", "akamaighost", "edgescape"],
            "aws_waf": ["awselb", "x-amzn-waf"],
            "f5": ["f5", "bigipserver", "tsig"],
            "imperva": ["incapsula", "imperva"],
        }
        detected = []
        headers_str = " ".join(f"{k}:{v}" for k, v in response_headers.items()).lower()
        body_lower = body[:2000].lower()
        for waf_name, signatures in waf_signatures.items():
            for sig in signatures:
                if sig in headers_str or sig in body_lower:
                    detected.append(waf_name)
                    break
        if status_code == 403 and not detected:
            detected.append("generic_waf")
        return {
            "detected_wafs": detected,
            "confidence": "HIGH" if len(detected) == 1 else ("MEDIUM" if detected else "NONE"),
            "status_code": status_code,
        }

    def get_adaptive_payloads(self, target: str, waf_type: str = "") -> Dict:
        """Get previously successful payloads + generate new ones."""
        return {
            "cached_successful": self._successful_payloads[-10:],
            "target": target,
            "waf_type": waf_type,
        }
