#!/usr/bin/env python3
"""DORAKULA Auto-Reporting & Validation Agent.

Template-based reports, severity calibration, evidence collection, PoC validation.
"""
import logging, json, time, os
from typing import Dict, List, Any
from datetime import datetime

logger = logging.getLogger(__name__)


class AutoReporter:
    """Generate professional security reports from scan results."""

    SEVERITY_ORDER = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "INFO": 0}

    CVSS_MAP = {
        "CRITICAL": {"score": 9.0, "range": "9.0-10.0"},
        "HIGH": {"score": 7.5, "range": "7.0-8.9"},
        "MEDIUM": {"score": 5.0, "range": "4.0-6.9"},
        "LOW": {"score": 2.5, "range": "0.1-3.9"},
        "INFO": {"score": 0.0, "range": "0.0"},
    }

    def __init__(self):
        self._reports_dir = "/tmp/dorakula_reports"
        os.makedirs(self._reports_dir, exist_ok=True)

    def calibrate_severity(self, finding: Dict) -> str:
        """Auto-calibrate severity based on finding context."""
        base_severity = finding.get("severity", "INFO").upper()
        # Upgrade if exploitable
        if finding.get("exploitable") or finding.get("vulnerable"):
            if base_severity == "MEDIUM":
                return "HIGH"
            if base_severity == "LOW":
                return "MEDIUM"
        # Downgrade if only informational
        if not finding.get("evidence") and not finding.get("response_snippet"):
            if base_severity in ("HIGH", "CRITICAL"):
                return "MEDIUM"
        return base_severity

    def generate_markdown_report(self, scan_results: Dict, target: str = "") -> str:
        """Generate a Markdown-format security report."""
        timestamp = datetime.utcnow().isoformat() + "Z"
        # Flatten all findings
        all_findings = []
        for category, results in scan_results.items():
            if isinstance(results, dict):
                for key, value in results.items():
                    if isinstance(value, dict) and "findings" in value:
                        for f in value["findings"]:
                            f["category"] = category
                            f["check"] = key
                            f["calibrated_severity"] = self.calibrate_severity(f)
                            all_findings.append(f)
                    elif isinstance(value, list):
                        for f in value:
                            if isinstance(f, dict):
                                f["category"] = category
                                f["calibrated_severity"] = self.calibrate_severity(f)
                                all_findings.append(f)

        # Sort by severity
        all_findings.sort(key=lambda x: self.SEVERITY_ORDER.get(x.get("calibrated_severity", "INFO"), 0), reverse=True)

        # Generate report
        report = f"""# DORAKULA Security Report

**Target:** {target}
**Date:** {timestamp}
**Total Findings:** {len(all_findings)}

## Executive Summary

| Severity | Count |
|----------|-------|
| CRITICAL | {sum(1 for f in all_findings if f.get("calibrated_severity") == "CRITICAL")} |
| HIGH     | {sum(1 for f in all_findings if f.get("calibrated_severity") == "HIGH")} |
| MEDIUM   | {sum(1 for f in all_findings if f.get("calibrated_severity") == "MEDIUM")} |
| LOW      | {sum(1 for f in all_findings if f.get("calibrated_severity") == "LOW")} |
| INFO     | {sum(1 for f in all_findings if f.get("calibrated_severity") == "INFO")} |

## Detailed Findings

"""
        for i, finding in enumerate(all_findings, 1):
            severity = finding.get("calibrated_severity", "INFO")
            cvss = self.CVSS_MAP.get(severity, {})
            report += f"""### Finding #{i}: {finding.get("check", finding.get("category", "Unknown"))}

- **Severity:** {severity}
- **CVSS (estimated):** {cvss.get("score", 0.0)} ({cvss.get("range", "N/A")})
- **Category:** {finding.get("category", "N/A")}
- **Description:** {finding.get("reason", finding.get("note", finding.get("error", "N/A")))}

"""
            if finding.get("evidence"):
                report += f"- **Evidence:** `{finding["evidence"][:200]}`\n"
            if finding.get("response_snippet"):
                report += f"- **Response:** `{finding["response_snippet"][:200]}`\n"
            if finding.get("payload"):
                report += f"- **Payload:** `{str(finding["payload"])[:100]}`\n"
            report += "\n"

        report += f"""## Remediation Recommendations

1. **CRITICAL/HIGH findings:** Fix immediately — these are actively exploitable.
2. **MEDIUM findings:** Plan remediation within 30 days.
3. **LOW/INFO findings:** Monitor and address in regular maintenance cycles.

---
*Report generated by DORAKULA v3.1.0 Auto-Reporter*
*This is an automated report — manual verification recommended for all findings.*
"""
        return report

    def generate_json_report(self, scan_results: Dict, target: str = "") -> Dict:
        """Generate a JSON-format security report."""
        return {
            "target": target,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "generator": "DORAKULA v3.1.0 Auto-Reporter",
            "scan_results": scan_results,
        }

    def save_report(self, report_content: str, target: str, format: str = "md") -> str:
        """Save report to file and return path."""
        safe_target = target.replace("://", "_").replace("/", "_").replace(".", "_")[:50]
        filename = f"{self._reports_dir}/dorakula_report_{safe_target}_{int(time.time())}.{format}"
        with open(filename, "w") as f:
            f.write(report_content)
        return filename

    def validate_poc(self, finding: Dict, target: str = "") -> Dict:
        """Validate a finding by attempting safe PoC verification."""
        return {
            "finding": finding.get("check", "unknown"),
            "target": target,
            "validation": "manual_review_required",
            "confidence": finding.get("calibrated_severity", "INFO"),
            "note": "Automated PoC validation requires target-specific configuration.",
        }
